=== gonpampinaicore/BarStockControl/BarStockControl.Data/Xml/data.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT data (
    permissions?,
    roles?,
    users?,
    products?,
    bars?,
    stations?,
    deposits?,
    stocks?,
    events?,
    drinks?,
    recipes?,
    recipeItems?,
    resourceAssignments?,
    resourceRolePermissions?,
    cashRegisters?,
    orders?,
    orderItems?,
    barmanOrders?,
    stockMovements?,
    stationProductConsumptions?
)>

<!-- ========== PERMISSIONS ========== -->
<!ELEMENT permissions (permission*)>
<!ELEMENT permission EMPTY>
<!ATTLIST permission
    id ID #REQUIRED
    name CDATA #REQUIRED
    description CDATA #REQUIRED
    isActive (true|false) "true"
>

<!-- ========== ROLES ========== -->
<!ELEMENT roles (role*)>
<!ELEMENT role (rolePermissionRef*)>
<!ELEMENT rolePermissionRef EMPTY>
<!ATTLIST rolePermissionRef
    ref IDREF #REQUIRED
>
<!ATTLIST role
    id ID #REQUIRED
    name CDATA #REQUIRED
    description CDATA #REQUIRED
    isActive (true|false) "true"
>

<!-- ========== USERS ========== -->
<!ELEMENT users (user*)>
<!ELEMENT user (roleRef)>
<!ELEMENT roleRef EMPTY>
<!ATTLIST roleRef
    ref IDREF #REQUIRED
>
<!ATTLIST user
    id ID #REQUIRED
    name CDATA #REQUIRED
    lastname CDATA #REQUIRED
    email CDATA #REQUIRED
    password CDATA #REQUIRED
    active (true|false) "true"
>

<!-- ========== RESOURCE ROLE PERMISSIONS ========== -->
<!ELEMENT resourceRolePermissions (resourceRolePermission*)>
<!ELEMENT resourceRolePermission EMPTY>
<!ATTLIST resourceRolePermission
    roleId IDREF #REQUIRED
    resourceType CDATA #REQUIRED
>

<!-- ========== PRODUCTS ========== -->
<!ELEMENT products (product*)>
<!ELEMENT product EMPTY>
<!ATTLIST product
    id ID #REQUIRED
    name CDATA #REQUIRED
    unit CDATA #REQUIRED
    category CDATA #REQUIRED
    capacity CDATA #REQUIRED
    price CDATA #REQUIRED
    estimatedServings CDATA #REQUIRED
    isActive (true|false) "true"
    type CDATA #REQUIRED
    qualityCategory CDATA #REQUIRED
    isImported (true|false) "true"
>

<!-- ========== BARS ========== -->
<!ELEMENT bars (bar*)>
<!ELEMENT bar EMPTY>
<!ATTLIST bar
    id ID #REQUIRED
    name CDATA #REQUIRED
    description CDATA #IMPLIED
    isActive (true|false) "true"
    active (true|false) "true"
>

<!-- ========== STATIONS ========== -->
<!ELEMENT stations (station*)>
<!ELEMENT station EMPTY>
<!ATTLIST station
    id ID #REQUIRED
    name CDATA #REQUIRED
    status CDATA #REQUIRED
    active (true|false) "true"
    comment CDATA #IMPLIED
    barId IDREF #REQUIRED
>

<!-- ========== DEPOSITS ========== -->
<!ELEMENT deposits (deposit*)>
<!ELEMENT deposit EMPTY>
<!ATTLIST deposit
    id ID #REQUIRED
    name CDATA #REQUIRED
    description CDATA #REQUIRED
    isActive (true|false) "true"
>

<!-- ========== STOCKS ========== -->
<!ELEMENT stocks (stock*)>
<!ELEMENT stock EMPTY>
<!ATTLIST stock
    id ID #REQUIRED
    productId IDREF #REQUIRED
    quantity CDATA #REQUIRED
    depositId IDREF #IMPLIED
    stationId IDREF #IMPLIED
>

<!-- ========== STOCK MOVEMENTS ========== -->
<!ELEMENT stockMovements (stockMovement*)>
<!ELEMENT stockMovement EMPTY>
<!ATTLIST stockMovement
    id ID #REQUIRED
    productId IDREF #REQUIRED
    quantity CDATA #REQUIRED
    eventId IDREF #REQUIRED
    requestedByUserId IDREF #REQUIRED
    timestamp CDATA #REQUIRED
    status CDATA #REQUIRED
    fromDepositId IDREF #IMPLIED
    toDepositId IDREF #IMPLIED
    fromStationId IDREF #IMPLIED
    toStationId IDREF #IMPLIED
    comment CDATA #IMPLIED
>

<!-- ========== EVENTS ========== -->
<!ELEMENT events (event*)>
<!ELEMENT event EMPTY>
<!ATTLIST event
    id ID #REQUIRED
    name CDATA #REQUIRED
    description CDATA #REQUIRED
    startDate CDATA #REQUIRED
    endDate CDATA #REQUIRED
    status CDATA #REQUIRED
    active (true|false) "true"
>

<!-- ========== DRINKS ========== -->
<!ELEMENT drinks (drink*)>
<!ELEMENT drink EMPTY>
<!ATTLIST drink
    id ID #REQUIRED
    name CDATA #REQUIRED
    price CDATA #REQUIRED
    isComposed (true|false) "true"
    isActive (true|false) "true"
    estimatedCost CDATA #REQUIRED
    createdAt CDATA #REQUIRED
    updatedAt CDATA #IMPLIED
>

<!-- ========== RECIPES ========== -->
<!ELEMENT recipes (recipe*)>
<!ELEMENT recipe EMPTY>
<!ATTLIST recipe
    id ID #REQUIRED
    drinkRef IDREF #REQUIRED
    name CDATA #REQUIRED
    isActive (true|false) "true"
>

<!-- ========== RECIPE ITEMS ========== -->
<!ELEMENT recipeItems (recipeItem*)>
<!ELEMENT recipeItem EMPTY>
<!ATTLIST recipeItem
    id ID #REQUIRED
    recipeRef IDREF #REQUIRED
    productRef IDREF #REQUIRED
    quantity CDATA #REQUIRED
    isActive (true|false) "true"
>

<!-- ========== RESOURCE ASSIGNMENTS ========== -->
<!ELEMENT resourceAssignments (resourceAssignment*)>
<!ELEMENT resourceAssignment EMPTY>
<!ATTLIST resourceAssignment
    id ID #REQUIRED
    eventId IDREF #REQUIRED
    resourceId IDREF #REQUIRED
    resourceType CDATA #REQUIRED
    userId IDREF #REQUIRED
>

<!-- ========== CASH REGISTERS ========== -->
<!ELEMENT cashRegisters (cashRegister*)>
<!ELEMENT cashRegister EMPTY>
<!ATTLIST cashRegister
    id ID #REQUIRED
    name CDATA #REQUIRED
    active (true|false) "true"
    barId IDREF #REQUIRED
>

<!-- ========== ORDERS ========== -->
<!ELEMENT orders (order*)>
<!ELEMENT order EMPTY>
<!ATTLIST order
    id ID #REQUIRED
    eventId IDREF #REQUIRED
    userId IDREF #REQUIRED
    createdAt CDATA #REQUIRED
    status CDATA #REQUIRED
    paymentMethod CDATA #REQUIRED
    total CDATA #REQUIRED
>

<!-- ========== ORDER ITEMS ========== -->
<!ELEMENT orderItems (orderItem*)>
<!ELEMENT orderItem EMPTY>
<!ATTLIST orderItem
    id ID #REQUIRED
    orderId IDREF #REQUIRED
    drinkId IDREF #REQUIRED
    quantity CDATA #REQUIRED
    unitPrice CDATA #REQUIRED
    discount CDATA #REQUIRED
    subtotal CDATA #REQUIRED
>

<!-- ========== BARMAN ORDERS ========== -->
<!ELEMENT barmanOrders (barmanOrder*)>
<!ELEMENT barmanOrder EMPTY>
<!ATTLIST barmanOrder
    id ID #REQUIRED
    orderId IDREF #REQUIRED
    barmanId IDREF #REQUIRED
    stationId IDREF #REQUIRED
    barId IDREF #REQUIRED
    eventId IDREF #REQUIRED
    dateTime CDATA #REQUIRED
>

<!-- ========== STATION PRODUCT CONSUMPTIONS ========== -->
<!ELEMENT stationProductConsumptions (stationProductConsumption*)>
<!ELEMENT stationProductConsumption EMPTY>
<!ATTLIST stationProductConsumption
    id ID #REQUIRED
    stationId IDREF #REQUIRED
    productId IDREF #REQUIRED
    orderItemId IDREF #REQUIRED
    fechaHora CDATA #REQUIRED
    eventoId IDREF #REQUIRED
    usuarioId IDREF #REQUIRED
>

=== gonpampinaicore/BarStockControl/BarStockControl.Data/Xml/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "data.dtd">
<data>
    <users>
    </users>
    <permissionItems>
    </permissionItems>
    <permissionDefs>
    </permissionDefs>
    <roles>
    </roles>
    <products>
    </products>
    <bars>
    </bars>
    <stations>
    </stations>
    <deposits>
    </deposits>
    <stocks>
    </stocks>
    <events>
    </events>
    <drinks>
    </drinks>
    <recipes>
    </recipes>
    <recipeItems>
    </recipeItems>
    <resourceAssignments>
    </resourceAssignments>
    <cashRegisters>
    </cashRegisters>
    <resourceRolePermissions>
    </resourceRolePermissions>
    <barmanOrders>
    </barmanOrders>
    <stationProductConsumptions>
    </stationProductConsumptions>
    <stockMovements>
    </stockMovements>
</data>
